name: Docker Build and Deploy

on:
  push:
    branches: [ master ]  
defaults:
    run:
      working-directory: nginx-docker-homepage
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_HUB_URL }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:nginx-docker-homepage"
        push: true
        tags: ${{ secrets.DOCKER_HUB_URL }}/${{ secrets.APPLICATION_NAME }}:${{ secrets.IMAGE_TAG }}
