# This is a basic workflow to help you get started with Actions

name: node-sample-test

on:
  push:
    branches: [ master ]
  
defaults:
    run:
      working-directory: sample-code/nodejs-sample

jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: node index.js
