name: node-sample-test
on:
  push:
    branches: [ master ]  
defaults:
    run:
      working-directory: sample-code/nodejs-sample
jobs:  
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2      
      - name: Build the docker image from Dockerfile
        run: docker build . --file Dockerfile --tag wriju/node-sample:v1
      - run: docker images

      - name: Azure Login
        # uses: azure/login@v1
        # with:
        #   creds: ${{secrets.AZURE_CRED}}
      - uses: azure/CLI@v1
      - run: az login --service-principal -u e250e4b6-6a4c-4681-bc0d-a0d24c9d78f2 -p UhlJKB_EvYVSxdD7E-hBoCKV-mx20HTTXC --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
      - run: az groups list
